apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    team: team-frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    team: team-production